name: nencarta_py312
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - beautifulsoup4
  - cython
  - dask
  - fiona
  - gdal
  - geoglows
  - geojson
  - geopandas
  - libgdal-arrow-parquet
  - netcdf4
  - numba
  - numpy
  - pandas
  - pipefunc
  - polars
  - progress
  - pyproj
  - pyqt>=5.15
  - requests
  - rich
  - s3fs
  - scipy
  - shapely
  - tqdm
  - xarray<2025.4.0
  - whitebox
  - zarr